import type { Supplier, Alert, DashboardMetrics } from "./types"

export const mockSuppliers: Supplier[] = [
  {
    id: "1",
    name: "TechCorp Solutions Pvt Ltd",
    gstin: "27AABCT1332L1ZZ",
    email: "contact@techcorp.com",
    phone: "+91-9876543210",
    address: "Mumbai, Maharashtra",
    category: "Critical",
    status: "Active",
    registrationDate: "2023-01-15",
    lastAuditDate: "2024-11-01",
    complianceScore: 92,
    riskLevel: "Low",
    documents: [
      {
        id: "1",
        name: "GST Certificate",
        type: "GST_Certificate",
        status: "Verified",
        uploadDate: "2023-01-15",
        expiryDate: "2025-01-15",
        url: "/documents/gst-cert-1.pdf",
      },
    ],
    kpis: [
      {
        id: "1",
        supplierId: "1",
        metric: "On-Time Delivery",
        value: 95,
        target: 90,
        unit: "%",
        period: "Monthly",
        status: "On_Track",
        lastUpdated: "2024-12-01",
      },
    ],
  },
  {
    id: "2",
    name: "Global Manufacturing Ltd",
    gstin: "29AABCG5647M1ZX",
    email: "info@globalmanuf.com",
    phone: "+91-9876543211",
    address: "Bangalore, Karnataka",
    category: "Important",
    status: "Active",
    registrationDate: "2023-03-20",
    lastAuditDate: "2024-10-15",
    complianceScore: 78,
    riskLevel: "Medium",
    documents: [],
    kpis: [],
  },
  {
    id: "3",
    name: "Quality Parts Inc",
    gstin: "24AABCQ9876P1ZY",
    email: "support@qualityparts.com",
    phone: "+91-9876543212",
    address: "Chennai, Tamil Nadu",
    category: "Standard",
    status: "Suspended",
    registrationDate: "2023-06-10",
    lastAuditDate: "2024-09-20",
    complianceScore: 45,
    riskLevel: "Critical",
    documents: [],
    kpis: [],
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "1",
    supplierId: "3",
    type: "Compliance",
    severity: "Critical",
    title: "GST Certificate Expired",
    description: "Quality Parts Inc GST certificate has expired and needs immediate renewal",
    status: "Open",
    createdDate: "2024-12-10",
    assignedTo: "John Doe",
  },
  {
    id: "2",
    supplierId: "2",
    type: "KPI",
    severity: "Medium",
    title: "Delivery Performance Below Target",
    description: "On-time delivery rate has dropped to 75% for the last quarter",
    status: "In_Progress",
    createdDate: "2024-12-08",
  },
]

export const mockDashboardMetrics: DashboardMetrics = {
  totalSuppliers: 156,
  activeSuppliers: 142,
  criticalAlerts: 8,
  avgComplianceScore: 82,
  suppliersAtRisk: 23,
  documentsExpiringSoon: 12,
  recentAudits: 34,
  kpiTrends: [
    { metric: "Compliance Score", current: 82, previous: 79, change: 3.8 },
    { metric: "On-Time Delivery", current: 87, previous: 85, change: 2.4 },
    { metric: "Quality Rating", current: 91, previous: 88, change: 3.4 },
  ],
}
